name: Rebuild Algolia

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == 'ayuhito'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Enable PNPM
        run: corepack enable

      - name: Install
        run: pnpm i

      - name: Generate fontlist
        run: pnpm run util:fontlist

      - name: Generate Algolia index
        run: pnpm run util:algolia
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}

      - name: Format files
        run: pnpm run format

      - name: Stage, commit and push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "fontsource-bot"
          commit_user_email: "83556432+fontsource-bot@users.noreply.github.com"
          commit_author: "fontsource-bot <83556432+fontsource-bot@users.noreply.github.com>"
          commit_message: "chore(build): update algolia"
        continue-on-error: true
