name: Build and Release [Force Rebuild No Deploy] [Manual]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == 'DecliningLotus'

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Configure CI Git User
        run: |
          git config --global user.name 'DecliningLotus'
          git config --global user.email 'DecliningLotus@users.noreply.github.com'

      - name: Install packages
        run: yarn

      - name: Fetch API
        run: npm explore google-font-metadata -- yarn parser:gen $GOOGLE_API_KEY
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Parse APIv1
        run: yarn parser:v1

      - name: Parse APIv2
        run: yarn parser:v2

      - name: Parse Variable
        run: yarn parser:variable

      - name: Build fonts (Google)
        run: yarn build:google-force

      - name: Rebuild non-Google fonts
        run: yarn build:generic-force

      - name: Generate fontlist
        run: yarn util:fontlist

      - name: Format files
        run: yarn format

      - name: Stage changes
        run: git add --all

      - name: Commit files
        run: >-
          git commit -m "chore(build): update fontsources [Force Rebuild $GITHUB_RUN_NUMBER]"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
