name: Build and Release [Manual]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == `DecliningLotus`

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Configure CI Git User
        run: |
          git config --global user.name 'DecliningLotus'
          git config --global user.email 'DecliningLotus@users.noreply.github.com'

      - name: Install packages
        run: yarn

      - name: Fetch API
        run: npm explore google-font-metadata -- node ./scripts/api-gen.js $GOOGLE_API_KEY
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Parse APIv1
        run: npm explore google-font-metadata -- yarn parser:v1

      - name: Build fonts
        run: yarn build:googlev1

      - name: Format files
        run: yarn format

      - name: Stage changes
        run: git add --all

      - name: Commit files
        run: >-
          git commit -m "chore(build): update fontsources $GITHUB_RUN_NUMBER"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish package
        run: npm run deploy:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
